### ISSUE TITLE
Responsive header

### ISSUE THREAD

**Issue by ivan-unfolds** [fac26/iman-derek-project-1#24]
The header feels a little crowded when looked at on mobile. Could it turn into a hamburger menu when on mobile?

<img width="489" alt="CleanShot 2022-10-04 at 19 46 19@2x" src="https://user-images.githubusercontent.com/12462448/193889875-a1dae268-81e9-44cd-9ff1-d04cd7a709ef.png">

**Comment by LL835** [comment]
Great idea - thank you! I will look into how to do that.

**Comment by ighellache** [comment]
Thanks Derek, the navbar looks great! Will close this now.
